import Header from '@/components/header';
import './global.css';
import  "bootstrap/dist/css/bootstrap.min.css";
import '../../../public/assets/css/custom-template.css';
import '../../../public/assets/css/meanmenu.min.css';
import '../../../public/assets/css/responsive.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
